apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-label-example
spec:
  action: pod-kill
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/component: router
