apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-example
spec:
  action: loss
  mode: one
  selector:
    pods:
      pxc-test:
        - percona-xtradb-cluster-operator-569867b9cd-htlm7
  loss:
    loss: "100"
    correlation: "100"
  duration: "60s"
