apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: percona-postgresql-operator-community
  source: percona-postgresql-operator
  sourceNamespace: community-test