apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: percona-postgresql-operator
  namespace: community-test
spec:
  displayName: Test Operators
  updateStrategy:
    registryPoll:
      interval: 5m
  image: docker.io/tishina/percona-postgresql-operator:2.3.2-community-bundle
  publisher: Red Hat Partner
  sourceType: grpc