apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: percona-server-mongodb-operator-community
  source: percona-mongodb-operator
  sourceNamespace: marketplace-community