apiVersion: v1
kind: Secret
metadata:
  name: cluster1-haproxy
data:
  haproxy-global.cfg: Z2xvYmFsCiAgbWF4Y29ubiA0MDk2CiAgZXh0ZXJuYWwtY2hlY2sKICBpbnNlY3VyZS1mb3JrLXdhbnRlZAogIHN0YXRzIHNvY2tldCAvdmFyL3J1bi9oYXByb3h5LnNvY2sgbW9kZSA2MDAgZXhwb3NlLWZkIGxpc3RlbmVycyBsZXZlbCB1c2VyCgpkZWZhdWx0cwogIGxvZyBnbG9iYWwKICBtb2RlIHRjcAogIHJldHJpZXMgMTAKICB0aW1lb3V0IGNsaWVudCAyODgwMHMKICB0aW1lb3V0IGNvbm5lY3QgMTAwNTAwCiAgdGltZW91dCBzZXJ2ZXIgMjg4MDBzCgpmcm9udGVuZCBnYWxlcmEtaW4KICBiaW5kICo6MzMwOSBhY2NlcHQtcHJveHkKICBiaW5kICo6MzMwNgogIG1vZGUgdGNwCiAgb3B0aW9uIGNsaXRjcGthCiAgZGVmYXVsdF9iYWNrZW5kIGdhbGVyYS1ub2RlcwoKZnJvbnRlbmQgZ2FsZXJhLXJlcGxpY2EtaW4KICBiaW5kICo6MzMwNwogIG1vZGUgdGNwCiAgb3B0aW9uIGNsaXRjcGthCiAgZGVmYXVsdF9iYWNrZW5kIGdhbGVyYS1yZXBsaWNhLW5vZGVzCg==
